#
# active spring boot profile
#
spring:
   profiles:
      active: development


---
#
# common configuration
#
spring:
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/static/
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML
      suffix : .html
      cache : false

# Eureka
eureka:
   client:
      fetchRegistry: true
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
         

---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
   devtools:
      livereload:
         enabled: true         

server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true


---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production    

server:
   port: 8882
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
