spring:
   application:
      name: mysite
   profiles:
      active: development
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML
      suffix : .html
      cache : false
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB
         

---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
   devtools:
      livereload:
         enabled: true
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
eureka:
   client:
      fetchRegistry: true
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO



---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production             
server:
   port: 8883
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
eureka:
   client:
      fetchRegistry: true
      registerWithEureka: false
      serviceUrl:
         defaultZone: http://49.247.9.194:8761/eureka
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            mysite:
               exception: ERROR
