spring:
  application:
    name: service-gateway-server
  profiles:
    active: development
server:
  port: 5555
management:
  endpoints:
    web:
      exposure:
        include: "*"
# 라우트임 
zuul:
  ignored-services: '*'
  prefix: ''
  routes:
    service-emaillist: /emaillist/**


---
#
# development configuration
#
spring:
   profiles: development
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO

---
#
# production configuration
#
spring:
   profiles: production
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://49.247.9.194:8761/eureka/
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN