spring:
   application:
      name: service-storage
   profiles:
      active: default

---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: default
      import: optional:configserver:http://localhost:7777


---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777


---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://49.247.9.194:7777